name: flutter_application_illumina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  date_picker_timeline: ^1.2.6
  flutter_localizations:
    sdk: flutter
  parse_server_sdk_flutter: ^8.0.0
  path: ^1.9.0
  table_calendar: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/image/
  uses-material-design: true
